/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSiftConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sift/v1
// Description:
//   API for sift

#import "GTLSiftConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeSiftUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
