/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLQuerySift.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sift/v1
// Description:
//   API for sift
// Classes:
//   GTLQuerySift (1 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLQuery.h"
#else
  #import "GTLQuery.h"
#endif

@class GTLSiftMainArticleRequest;

@interface GTLQuerySift : GTLQuery

//
// Parameters valid on all methods.
//

// Selector specifying which fields to include in a partial response.
@property (copy) NSString *fields;

#pragma mark -
#pragma mark "siftApi" methods
// These create a GTLQuerySift object.

// Method: sift.siftApi.getArticles
//  Authorization scope(s):
//   kGTLAuthScopeSiftUserinfoEmail
// Fetches a GTLSiftMainArticleResponse.
+ (id)queryForSiftApiGetArticlesWithObject:(GTLSiftMainArticleRequest *)object;

@end
