/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSiftMainArticleResponse.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sift/v1
// Description:
//   API for sift
// Classes:
//   GTLSiftMainArticleResponse (0 custom class methods, 1 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLSiftMainArticle;

// ----------------------------------------------------------------------------
//
//   GTLSiftMainArticleResponse
//

@interface GTLSiftMainArticleResponse : GTLObject
@property (retain) NSArray *articles;  // of GTLSiftMainArticle
@end
