/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSiftMainArticle.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sift/v1
// Description:
//   API for sift
// Classes:
//   GTLSiftMainArticle (0 custom class methods, 8 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLSiftMainArticle
//

@interface GTLSiftMainArticle : GTLObject
@property (copy) NSString *author;
@property (copy) NSString *fullArticle;
@property (copy) NSString *imageUrl;
@property (copy) NSString *publication;
@property (copy) NSString *published;
@property (retain) NSNumber *publishedTimestamp;  // longLongValue
@property (copy) NSString *summarizedArticle;
@property (copy) NSString *title;
@end
