/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSiftMainUpvoteRequest.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sift/v1
// Description:
//   API for sift
// Classes:
//   GTLSiftMainUpvoteRequest (0 custom class methods, 2 custom properties)

#import "GTLSiftMainUpvoteRequest.h"

// ----------------------------------------------------------------------------
//
//   GTLSiftMainUpvoteRequest
//

@implementation GTLSiftMainUpvoteRequest
@dynamic articleTitle, userId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObjectsAndKeys:
      @"article_title", @"articleTitle",
      @"user_id", @"userId",
      nil];
  return map;
}

@end
