/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSift.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sift/v1
// Description:
//   API for sift

#import "GTLSiftConstants.h"

#import "GTLSiftMainArticle.h"
#import "GTLSiftMainArticleRequest.h"
#import "GTLSiftMainArticleResponse.h"

#import "GTLQuerySift.h"
#import "GTLServiceSift.h"
