/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSiftMainUpvoteResponse.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sift/v1
// Description:
//   API for sift
// Classes:
//   GTLSiftMainUpvoteResponse (0 custom class methods, 1 custom properties)

#import "GTLSiftMainUpvoteResponse.h"

// ----------------------------------------------------------------------------
//
//   GTLSiftMainUpvoteResponse
//

@implementation GTLSiftMainUpvoteResponse
@dynamic articleUpvotes;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map =
    [NSDictionary dictionaryWithObject:@"article_upvotes"
                                forKey:@"articleUpvotes"];
  return map;
}

@end
