/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2015 Google Inc.
 */

//
//  GTLSift_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   sift/v1
// Description:
//   API for sift

#import "GTLSiftConstants.m"

#import "GTLSiftMainArticle.m"
#import "GTLSiftMainArticleRequest.m"
#import "GTLSiftMainArticleResponse.m"
#import "GTLSiftMainUpvoteRequest.m"
#import "GTLSiftMainUpvoteResponse.m"

#import "GTLQuerySift.m"
#import "GTLServiceSift.m"
